project_name: pocketbase

dist: dist

before:
  hooks:
    - go mod tidy

builds:
  - main: ./extended/main.go
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
- format: binary

snapshot:
  name_template: '{{ incpatch .Version }}-next'
